#It's a comment!
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: github-demo-lambda-pix

  ImageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ImageBucket
        PolicyDocument:
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Principal: "*"
              Resource: !Sub arn:aws:s3:::github-demo-lambda-pix/*

  ResizedBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: github-demo-lambda-pix-resized

  ResizeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResizedBucket
      PolicyDocument:
        Statement:
          - Action: s3:PutObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::github-demo-lambda-pix-resized/*

  ResizeFunction:
        Type: AWS::Serverless::Function
        Properties:
          #CodeUri: ./dist/github-demo-lambda_latest.zip
          #CodeUri: s3://github-demo-lambda/github-lambda-demo_latest.zip
          CodeUri: ./
          Handler: index.handler
          Runtime: nodejs6.10
          MemorySize: 1024
          Timeout: 300
          FunctionName: CreateThumbnail
          Role: arn:aws:iam::767259522535:role/lambda-demo-admin-role
          Environment:
                  Variables:
                    BUCKET: Bucket
                    URL: Url

  PixBucketLambdaPerm:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ResizeFunction
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::Join:
        - ":"
        - - arn
          - aws
          - s3
          - ''
          - ''
          - github-demo-lambda-pix

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: github-demo-lambda-pix
      Tags: []
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: s3:ObjectCreated:*
          Function:
            Fn::GetAtt:
            - ResizeFunction
            - Arn
